#include "autotune_entry.hpp"

#include "autotune_manager.hpp"
#include "autotune_persist.hpp"
#include "autotune_runner.hpp"
#include "autotune_types.hpp"

#include "n0s/misc/console.hpp"
#include "n0s/params.hpp"
#include "n0s/version.hpp"

#include <array>
#include <cstdio>
#include <set>
#include <sstream>
#include <string>
#include <vector>

// Cross-platform popen/pclose via compat layer
#include "n0s/platform/compat.hpp"

namespace n0s
{
namespace autotune
{

namespace
{

/// Parse comma-separated GPU indices from string
std::set<uint32_t> parseGpuIndices(const std::string& str)
{
	std::set<uint32_t> indices;
	if(str.empty()) return indices;

	std::istringstream ss(str);
	uint32_t idx;
	while(ss >> idx)
	{
		indices.insert(idx);
		while(ss.peek() == ',' || ss.peek() == ' ')
			ss.ignore();
	}
	return indices;
}

TuneMode parseTuneMode(const std::string& str)
{
	if(str == "quick") return TuneMode::Quick;
	if(str == "exhaustive") return TuneMode::Exhaustive;
	return TuneMode::Balanced;
}

TuneTarget parseTuneTarget(const std::string& str)
{
	if(str == "efficiency") return TuneTarget::Efficiency;
	if(str == "balanced") return TuneTarget::Balanced;
	return TuneTarget::Hashrate;
}

/// Discover all NVIDIA GPU indices via nvidia-smi
std::vector<uint32_t> discoverNvidiaGpus()
{
	std::vector<uint32_t> gpus;
#ifdef _WIN32
	FILE* pipe = n0s::compat::popen("nvidia-smi --query-gpu=index --format=csv,noheader 2>nul", "r");
#else
	FILE* pipe = n0s::compat::popen("nvidia-smi --query-gpu=index --format=csv,noheader 2>/dev/null", "r");
#endif
	if(!pipe) return gpus;

	std::array<char, 128> buf;
	while(fgets(buf.data(), buf.size(), pipe))
	{
		std::string line(buf.data());
		// Trim whitespace
		line.erase(line.find_last_not_of(" \t\n\r") + 1);
		if(!line.empty() && line[0] >= '0' && line[0] <= '9')
		{
			try { gpus.push_back(std::stoul(line)); } catch(...) {}
		}
	}
	n0s::compat::pclose(pipe);
	return gpus;
}

/// Discover all AMD/OpenCL GPU device count via clinfo
/// Returns indices [0..N-1] for N devices found
std::vector<uint32_t> discoverAmdGpus()
{
	std::vector<uint32_t> gpus;
#ifdef _WIN32
	FILE* pipe = n0s::compat::popen("clinfo 2>nul", "r");
#else
	FILE* pipe = n0s::compat::popen("clinfo 2>/dev/null | grep 'Number of devices' | head -1", "r");
#endif
	if(!pipe)
	{
		gpus.push_back(0); // Fallback: assume at least GPU 0
		return gpus;
	}

	std::array<char, 256> buf;
	std::string output;
	while(fgets(buf.data(), buf.size(), pipe))
		output += buf.data();
	n0s::compat::pclose(pipe);

	// Parse "Number of devices                              1"
	auto pos = output.rfind(' ');
	if(pos != std::string::npos)
	{
		std::string num_str = output.substr(pos + 1);
		num_str.erase(num_str.find_last_not_of(" \t\n\r") + 1);
		try
		{
			uint32_t count = std::stoul(num_str);
			for(uint32_t i = 0; i < count; i++)
				gpus.push_back(i);
		}
		catch(...)
		{
			gpus.push_back(0);
		}
	}
	else
	{
		gpus.push_back(0);
	}

	return gpus;
}

/// Collected autotune result for a single GPU
struct GpuWinner
{
	uint32_t device_index;
	bool is_amd;
	AmdCandidate amd;
	NvidiaCandidate nvidia;
	std::string gpu_name;
};

/// Write AMD config with ALL tuned GPUs in a single file
bool writeAmdConfigMulti(const std::vector<GpuWinner>& winners, const std::string& config_path)
{
	FILE* f = fopen(config_path.c_str(), "w");
	if(!f) return false;

	fprintf(f, "// Generated by n0s-ryo-miner --autotune\n");
	fprintf(f, "// %zu GPU(s) tuned\n\n", winners.size());
	fprintf(f, "\"gpu_threads_conf\" : [\n");

	for(size_t i = 0; i < winners.size(); i++)
	{
		const auto& w = winners[i];
		fprintf(f, "  // GPU %u: %s — intensity=%zu worksize=%zu\n",
			w.device_index, w.gpu_name.c_str(), w.amd.intensity, w.amd.worksize);
		fprintf(f, "  { \"index\" : %u,\n", w.device_index);
		fprintf(f, "    \"intensity\" : %zu, \"worksize\" : %zu,\n", w.amd.intensity, w.amd.worksize);
		fprintf(f, "    \"affine_to_cpu\" : false, \"strided_index\" : 0, \"mem_chunk\" : 2,\n");
		fprintf(f, "    \"unroll\" : 1, \"comp_mode\" : true, \"interleave\" : 40\n");
		fprintf(f, "  },\n");
	}

	fprintf(f, "],\n\n");
	fprintf(f, "\"auto_tune\" : 0,\n");
	fprintf(f, "\"platform_index\" : 0,\n");
	fclose(f);

	printer::inst()->print_msg(L0, "AUTOTUNE: AMD config written to %s (%zu GPU%s)",
		config_path.c_str(), winners.size(), winners.size() == 1 ? "" : "s");
	return true;
}

/// Write NVIDIA config with ALL tuned GPUs in a single file
bool writeNvidiaConfigMulti(const std::vector<GpuWinner>& winners, const std::string& config_path)
{
	FILE* f = fopen(config_path.c_str(), "w");
	if(!f) return false;

	fprintf(f, "// Generated by n0s-ryo-miner --autotune\n");
	fprintf(f, "// %zu GPU(s) tuned\n\n", winners.size());
	fprintf(f, "\"gpu_threads_conf\" :\n[\n");

	for(size_t i = 0; i < winners.size(); i++)
	{
		const auto& w = winners[i];
		fprintf(f, "  // GPU %u: %s — threads=%u blocks=%u bfactor=%u\n",
			w.device_index, w.gpu_name.c_str(), w.nvidia.threads, w.nvidia.blocks, w.nvidia.bfactor);
		fprintf(f, "  { \"index\" : %u,\n", w.device_index);
		fprintf(f, "    \"threads\" : %u, \"blocks\" : %u,\n", w.nvidia.threads, w.nvidia.blocks);
		fprintf(f, "    \"bfactor\" : %u, \"bsleep\" : 0,\n", w.nvidia.bfactor);
		fprintf(f, "    \"affine_to_cpu\" : false, \"sync_mode\" : 3,\n");
		fprintf(f, "    \"mem_mode\" : 1,\n");
		fprintf(f, "  },\n");
	}

	fprintf(f, "],\n");
	fclose(f);

	printer::inst()->print_msg(L0, "AUTOTUNE: NVIDIA config written to %s (%zu GPU%s)",
		config_path.c_str(), winners.size(), winners.size() == 1 ? "" : "s");
	return true;
}

} // anonymous namespace

int do_autotune()
{
	auto& p = params::inst();

	printer::inst()->print_msg(L0, "");
	printer::inst()->print_msg(L0, "╔══════════════════════════════════════════╗");
	printer::inst()->print_msg(L0, "║       n0s-ryo-miner AUTOTUNE            ║");
	printer::inst()->print_msg(L0, "║  Finding optimal GPU settings...         ║");
	printer::inst()->print_msg(L0, "╚══════════════════════════════════════════╝");
	printer::inst()->print_msg(L0, "");

	// Build config from params
	AutotuneConfig config;
	config.mode = parseTuneMode(p.autotune_mode);
	config.target = parseTuneTarget(p.autotune_target);
	config.backend_filter = p.autotune_backend;
	config.gpu_indices = parseGpuIndices(p.autotune_gpus);
	config.reset = p.autotune_reset;
	config.resume = p.autotune_resume;
	config.benchmark_seconds = p.autotune_benchmark_sec;
	config.stability_seconds = p.autotune_stability_sec;
	config.autotune_file = p.autotune_file;

	printer::inst()->print_msg(L0, "AUTOTUNE: Mode=%s Target=%s Backend=%s Benchmark=%ds Stability=%ds",
		p.autotune_mode.c_str(), p.autotune_target.c_str(), p.autotune_backend.c_str(),
		config.benchmark_seconds, config.stability_seconds);

	// Find the miner binary path
	std::string miner_path = p.minerArg0;
	if(miner_path.empty())
	{
		printer::inst()->print_msg(L0, "AUTOTUNE: ERROR — cannot determine miner binary path");
		return 1;
	}

	SubprocessRunner runner(miner_path);
	AutotuneManager manager(config);

	// Collect winners from all GPUs, then write config files once at the end
	std::vector<GpuWinner> amd_winners;
	std::vector<GpuWinner> nvidia_winners;

	// AMD/OpenCL devices
	bool tune_amd = (config.backend_filter == "all" || config.backend_filter == "amd");
	bool tune_nvidia = (config.backend_filter == "all" || config.backend_filter == "nvidia");

#ifndef CONF_NO_OPENCL
	if(tune_amd && p.useAMD)
	{
		printer::inst()->print_msg(L0, "AUTOTUNE: Scanning AMD/OpenCL devices...");

		// Discover AMD GPUs — auto-detect all if no --autotune-gpu specified
		std::vector<uint32_t> amd_devices;
		if(config.gpu_indices.empty())
		{
			amd_devices = discoverAmdGpus();
			printer::inst()->print_msg(L0, "AUTOTUNE: Auto-discovered %zu AMD/OpenCL device(s)",
				amd_devices.size());
		}
		else
		{
			for(auto idx : config.gpu_indices)
				amd_devices.push_back(idx);
		}

		for(uint32_t dev_idx : amd_devices)
		{
			DeviceFingerprint fp;
			if(!runner.collectAmdFingerprint(dev_idx, fp))
			{
				printer::inst()->print_msg(L0, "AUTOTUNE: Failed to collect fingerprint for AMD GPU %u", dev_idx);
				continue;
			}

			printer::inst()->print_msg(L0, "AUTOTUNE: AMD GPU %u: %s (%u CUs, %zu MiB VRAM)",
				dev_idx, fp.gpu_name.c_str(), fp.compute_units,
				fp.vram_bytes / (1024 * 1024));

			// Create evaluator callback
			auto evaluator = [&runner](uint32_t device_index, const CandidateRecord& candidate,
				int benchmark_sec, BenchmarkMetrics& metrics) -> bool {
				return runner.evaluateAmd(device_index, candidate, benchmark_sec, metrics);
			};

			const CandidateRecord* best = manager.tuneDevice(dev_idx, fp, evaluator);
			if(best)
			{
				GpuWinner winner;
				winner.device_index = dev_idx;
				winner.is_amd = true;
				winner.amd = best->amd;
				winner.gpu_name = fp.gpu_name;
				amd_winners.push_back(winner);
			}
		}
	}
#endif

#ifndef CONF_NO_CUDA
	if(tune_nvidia && p.useNVIDIA)
	{
		printer::inst()->print_msg(L0, "AUTOTUNE: Scanning NVIDIA/CUDA devices...");

		// Discover NVIDIA GPUs — auto-detect all if no --autotune-gpu specified
		std::vector<uint32_t> nv_devices;
		if(config.gpu_indices.empty())
		{
			nv_devices = discoverNvidiaGpus();
			if(nv_devices.empty())
			{
				printer::inst()->print_msg(L0, "AUTOTUNE: No NVIDIA GPUs discovered via nvidia-smi");
			}
			else
			{
				printer::inst()->print_msg(L0, "AUTOTUNE: Auto-discovered %zu NVIDIA device(s)",
					nv_devices.size());
			}
		}
		else
		{
			for(auto idx : config.gpu_indices)
				nv_devices.push_back(idx);
		}

		for(uint32_t dev_idx : nv_devices)
		{
			DeviceFingerprint fp;
			if(!runner.collectNvidiaFingerprint(dev_idx, fp))
			{
				printer::inst()->print_msg(L0, "AUTOTUNE: Failed to collect fingerprint for NVIDIA GPU %u", dev_idx);
				continue;
			}

			printer::inst()->print_msg(L0, "AUTOTUNE: NVIDIA GPU %u: %s (%s, %u SMs, %zu MiB VRAM)",
				dev_idx, fp.gpu_name.c_str(), fp.gpu_architecture.c_str(),
				fp.compute_units, fp.vram_bytes / (1024 * 1024));

			auto evaluator = [&runner](uint32_t device_index, const CandidateRecord& candidate,
				int benchmark_sec, BenchmarkMetrics& metrics) -> bool {
				return runner.evaluateNvidia(device_index, candidate, benchmark_sec, metrics);
			};

			const CandidateRecord* best = manager.tuneDevice(dev_idx, fp, evaluator);
			if(best)
			{
				GpuWinner winner;
				winner.device_index = dev_idx;
				winner.is_amd = false;
				winner.nvidia = best->nvidia;
				winner.gpu_name = fp.gpu_name;
				nvidia_winners.push_back(winner);
			}
		}
	}
#endif

	// Write config files with ALL winners (not one-GPU-at-a-time)
	bool any_success = false;

	if(!amd_winners.empty())
	{
		writeAmdConfigMulti(amd_winners, p.configFileAMD);
		any_success = true;
	}

	if(!nvidia_winners.empty())
	{
		writeNvidiaConfigMulti(nvidia_winners, p.configFileNVIDIA);
		any_success = true;
	}

	// Save final results
	const auto& result = manager.getResult();
	saveAutotuneResult(result, config.autotune_file);

	// Optional export
	if(!p.autotune_export.empty())
	{
		saveAutotuneResult(result, p.autotune_export);
		printer::inst()->print_msg(L0, "AUTOTUNE: Results exported to %s", p.autotune_export.c_str());
	}

	if(any_success)
	{
		printer::inst()->print_msg(L0, "");
		printer::inst()->print_msg(L0, "╔══════════════════════════════════════════╗");
		printer::inst()->print_msg(L0, "║       AUTOTUNE COMPLETE ✓                ║");
		printer::inst()->print_msg(L0, "║  Config files written. Run without       ║");
		printer::inst()->print_msg(L0, "║  --autotune to start mining.             ║");
		printer::inst()->print_msg(L0, "╚══════════════════════════════════════════╝");
		return 0;
	}
	else
	{
		printer::inst()->print_msg(L0, "AUTOTUNE: No GPU was successfully tuned.");
		return 1;
	}
}

} // namespace autotune
} // namespace n0s
